import type { GroceryCategory } from '@/types/grocery'

// Evaluated in order — first substring match wins.
// IMPORTANT: more specific keywords must appear before shorter ones that could match.
// e.g. 'bell pepper' before 'pepper', 'frozen' before produce keywords, 'basil' in produce before spices.
const KEYWORD_MAP: Array<[string, GroceryCategory]> = [
  // frozen — checked first so "frozen corn" → frozen, not produce
  ['frozen', 'frozen'],
  ['ice cream', 'frozen'],
  ['sorbet', 'frozen'],

  // produce
  ['tomato', 'produce'],
  ['lettuce', 'produce'],
  ['spinach', 'produce'],
  ['kale', 'produce'],
  ['arugula', 'produce'],
  ['broccoli', 'produce'],
  ['cauliflower', 'produce'],
  ['zucchini', 'produce'],
  ['cucumber', 'produce'],
  ['celery', 'produce'],
  ['carrot', 'produce'],
  ['bell pepper', 'produce'], // must be before 'pepper'
  ['jalapeño', 'produce'],
  ['jalapeno', 'produce'],
  ['green onion', 'produce'],
  ['scallion', 'produce'],
  ['shallot', 'produce'],
  ['onion', 'produce'],
  ['garlic', 'produce'],
  ['ginger', 'produce'],
  ['sweet potato', 'produce'],
  ['potato', 'produce'],
  ['yam', 'produce'],
  ['corn', 'produce'],
  ['mushroom', 'produce'],
  ['eggplant', 'produce'],
  ['asparagus', 'produce'],
  ['green bean', 'produce'],
  ['snap pea', 'produce'],
  ['avocado', 'produce'],
  ['apple', 'produce'],
  ['banana', 'produce'],
  ['lemon', 'produce'],
  ['lime', 'produce'],
  ['orange', 'produce'],
  ['strawberr', 'produce'],
  ['blueberr', 'produce'],
  ['raspberr', 'produce'],
  ['blackberr', 'produce'],
  ['grape', 'produce'],
  ['peach', 'produce'],
  ['mango', 'produce'],
  ['pineapple', 'produce'],
  // fresh herbs in produce (before spices section)
  ['cilantro', 'produce'],
  ['parsley', 'produce'],
  ['basil', 'produce'],
  ['mint', 'produce'],
  ['dill', 'produce'],
  ['chive', 'produce'],
  ['thyme', 'produce'],
  ['rosemary', 'produce'],
  ['sage', 'produce'],
  ['tarragon', 'produce'],
  ['herb', 'produce'],

  // proteins
  ['chicken', 'proteins'],
  ['turkey', 'proteins'],
  ['ground beef', 'proteins'],
  ['beef', 'proteins'],
  ['steak', 'proteins'],
  ['pork', 'proteins'],
  ['bacon', 'proteins'],
  ['sausage', 'proteins'],
  ['lamb', 'proteins'],
  ['salmon', 'proteins'],
  ['tuna', 'proteins'],
  ['shrimp', 'proteins'],
  ['cod', 'proteins'],
  ['tilapia', 'proteins'],
  ['halibut', 'proteins'],
  ['scallop', 'proteins'],
  ['crab', 'proteins'],
  ['lobster', 'proteins'],
  ['tofu', 'proteins'],
  ['tempeh', 'proteins'],
  ['edamame', 'proteins'],
  ['lentil', 'proteins'],
  ['chickpea', 'proteins'],
  ['black bean', 'proteins'],
  ['kidney bean', 'proteins'],
  ['white bean', 'proteins'],
  ['pinto bean', 'proteins'],
  ['cannellini', 'proteins'],
  ['garbanzo', 'proteins'],
  ['navy bean', 'proteins'],
  ['great northern', 'proteins'],
  ['fava bean', 'proteins'],
  ['adzuki', 'proteins'],
  ['bean', 'proteins'], // generic fallback — 'green bean' (produce) appears earlier and wins
  ['egg', 'proteins'],

  // dairy
  ['cream cheese', 'dairy'],
  ['sour cream', 'dairy'],
  ['half and half', 'dairy'],
  ['heavy cream', 'dairy'],
  ['whipping cream', 'dairy'],
  ['milk', 'dairy'],
  ['butter', 'dairy'],
  ['ghee', 'dairy'],
  ['mozzarella', 'dairy'],
  ['parmesan', 'dairy'],
  ['cheddar', 'dairy'],
  ['feta', 'dairy'],
  ['ricotta', 'dairy'],
  ['brie', 'dairy'],
  ['gouda', 'dairy'],
  ['cheese', 'dairy'],
  ['cream', 'dairy'],
  ['yogurt', 'dairy'],
  ['kefir', 'dairy'],

  // bakery
  ['baguette', 'bakery'],
  ['sourdough', 'bakery'],
  ['bread', 'bakery'],
  ['tortilla', 'bakery'],
  ['pita', 'bakery'],
  ['bagel', 'bakery'],
  ['muffin', 'bakery'],
  ['croissant', 'bakery'],
  ['bun', 'bakery'],
  ['roll', 'bakery'],
  ['naan', 'bakery'],
  ['wrap', 'bakery'],

  // beverages
  ['juice', 'beverages'],
  ['wine', 'beverages'],
  ['beer', 'beverages'],
  ['coffee', 'beverages'],
  ['tea', 'beverages'],
  ['sparkling water', 'beverages'],
  ['soda', 'beverages'],
  ['broth', 'beverages'], // wait, broth is pantry — but let's keep pantry below
  ['stock', 'beverages'], // same issue — actually broth/stock should be pantry

  // pantry (shelf-stable)
  ['flour', 'pantry'],
  ['sugar', 'pantry'],
  ['honey', 'pantry'],
  ['maple syrup', 'pantry'],
  ['olive oil', 'pantry'],
  ['vegetable oil', 'pantry'],
  ['canola oil', 'pantry'],
  ['coconut oil', 'pantry'],
  ['sesame oil', 'pantry'],
  ['oil', 'pantry'],
  ['spaghetti', 'pantry'],
  ['pasta', 'pantry'],
  ['noodle', 'pantry'],
  ['rice', 'pantry'],
  ['quinoa', 'pantry'],
  ['oat', 'pantry'],
  ['bread crumb', 'pantry'],
  ['panko', 'pantry'],
  ['chicken broth', 'pantry'],
  ['vegetable broth', 'pantry'],
  ['beef broth', 'pantry'],
  ['broth', 'pantry'],
  ['stock', 'pantry'],
  ['bouillon', 'pantry'],
  ['canned', 'pantry'],
  ['tomato paste', 'pantry'],
  ['tomato sauce', 'pantry'],
  ['coconut milk', 'pantry'],
  ['vinegar', 'pantry'],
  ['soy sauce', 'pantry'],
  ['tamari', 'pantry'],
  ['fish sauce', 'pantry'],
  ['worcestershire', 'pantry'],
  ['hot sauce', 'pantry'],
  ['sriracha', 'pantry'],
  ['ketchup', 'pantry'],
  ['mustard', 'pantry'],
  ['mayo', 'pantry'],
  ['mayonnaise', 'pantry'],
  ['tahini', 'pantry'],
  ['peanut butter', 'pantry'],
  ['almond butter', 'pantry'],
  ['jam', 'pantry'],
  ['baking powder', 'pantry'],
  ['baking soda', 'pantry'],
  ['cornstarch', 'pantry'],
  ['yeast', 'pantry'],
  ['vanilla', 'pantry'],
  ['chocolate', 'pantry'],
  ['cocoa', 'pantry'],
  ['almond', 'pantry'],
  ['walnut', 'pantry'],
  ['cashew', 'pantry'],
  ['pecan', 'pantry'],
  ['pine nut', 'pantry'],
  ['peanut', 'pantry'],
  ['nut', 'pantry'],
  ['seed', 'pantry'],
  ['raisin', 'pantry'],
  ['dried cranberr', 'pantry'],
  ['lentil', 'pantry'],

  // spices
  ['salt', 'spices'],
  ['black pepper', 'spices'],
  ['pepper', 'spices'], // after 'bell pepper' so this catches "black pepper", "white pepper"
  ['cumin', 'spices'],
  ['paprika', 'spices'],
  ['cinnamon', 'spices'],
  ['oregano', 'spices'],
  ['turmeric', 'spices'],
  ['chili powder', 'spices'],
  ['cayenne', 'spices'],
  ['curry', 'spices'],
  ['coriander', 'spices'],
  ['cardamom', 'spices'],
  ['clove', 'spices'],
  ['nutmeg', 'spices'],
  ['allspice', 'spices'],
  ['bay leaf', 'spices'],
  ['bay leave', 'spices'],
  ['garlic powder', 'spices'],
  ['onion powder', 'spices'],
  ['smoked paprika', 'spices'],
  ['red pepper flake', 'spices'],
  ['italian seasoning', 'spices'],
  ['cumin', 'spices'],
  ['fennel', 'spices'],
  ['anise', 'spices'],
]

export function categorize(ingredientName: string): GroceryCategory {
  const lower = ingredientName.toLowerCase()
  for (const [keyword, category] of KEYWORD_MAP) {
    if (lower.includes(keyword.toLowerCase())) return category
  }
  return 'other'
}

export const CATEGORY_ORDER: GroceryCategory[] = [
  'produce',
  'proteins',
  'dairy',
  'bakery',
  'pantry',
  'spices',
  'frozen',
  'beverages',
  'other',
]

export const CATEGORY_LABELS: Record<GroceryCategory, string> = {
  produce: 'Produce',
  proteins: 'Proteins',
  dairy: 'Dairy',
  bakery: 'Bakery',
  pantry: 'Pantry',
  spices: 'Spices & Herbs',
  frozen: 'Frozen',
  beverages: 'Beverages',
  other: 'Other',
}
