// Shelf life in days after purchase.
// Lookup is keyword-based: evaluates entries in order, returns first match.
// If no match, returns DEFAULT_SHELF_LIFE_DAYS.
const SHELF_LIFE_MAP: Array<[string, number]> = [
  // Proteins — very short
  ['chicken', 2],
  ['ground beef', 2],
  ['ground turkey', 2],
  ['ground pork', 2],
  ['beef', 3],
  ['steak', 3],
  ['pork', 3],
  ['lamb', 3],
  ['fish', 2],
  ['salmon', 2],
  ['tuna', 2],
  ['shrimp', 2],
  ['scallop', 2],
  ['crab', 2],
  ['lobster', 2],
  ['seafood', 2],

  // Proteins — medium
  ['bacon', 7],
  ['sausage', 5],
  ['deli', 5],
  ['tofu', 7],
  ['tempeh', 7],

  // Dairy — short to medium
  ['milk', 7],
  ['heavy cream', 7],
  ['whipping cream', 7],
  ['sour cream', 14],
  ['cream', 7],
  ['yogurt', 14],
  ['butter', 30],
  ['ghee', 90],
  ['ricotta', 7],
  ['mozzarella', 7],
  ['brie', 14],
  ['cream cheese', 14],
  ['cheese', 21],
  ['egg', 21],
  ['kefir', 14],

  // Produce — very short
  ['arugula', 4],
  ['spinach', 5],
  ['cilantro', 5],
  ['parsley', 5],
  ['basil', 5],
  ['dill', 5],
  ['mint', 5],
  ['chive', 5],
  ['herb', 5],
  ['strawberr', 4],
  ['raspberr', 3],
  ['blackberr', 3],
  ['blueberr', 7],
  ['lettuce', 7],
  ['kale', 7],
  ['asparagus', 4],
  ['corn', 3],
  ['avocado', 3],
  ['banana', 5],
  ['mushroom', 7],
  ['broccoli', 7],
  ['cauliflower', 10],
  ['green bean', 7],

  // Produce — medium
  ['tomato', 10],
  ['zucchini', 10],
  ['cucumber', 10],
  ['bell pepper', 14],
  ['pepper', 14],
  ['celery', 14],
  ['grape', 10],
  ['peach', 7],
  ['mango', 7],
  ['pineapple', 7],
  ['lemon', 21],
  ['lime', 21],
  ['orange', 21],
  ['apple', 30],
  ['carrot', 21],
  ['sweet potato', 30],
  ['potato', 60],
  ['onion', 60],
  ['shallot', 30],
  ['garlic', 60],
  ['ginger', 21],

  // Bakery
  ['baguette', 2],
  ['bread', 5],
  ['bagel', 5],
  ['tortilla', 14],
  ['pita', 7],
  ['naan', 5],
  ['roll', 5],
  ['bun', 5],

  // Pantry — long
  ['pasta', 365],
  ['spaghetti', 365],
  ['noodle', 365],
  ['rice', 365],
  ['quinoa', 365],
  ['oat', 365],
  ['flour', 365],
  ['sugar', 730],
  ['brown sugar', 730],
  ['honey', 730],
  ['maple syrup', 365],
  ['olive oil', 60],
  ['vegetable oil', 90],
  ['canola oil', 90],
  ['coconut oil', 180],
  ['sesame oil', 60],
  ['oil', 60],
  ['canned', 730],
  ['broth', 180],
  ['stock', 180],
  ['bouillon', 365],
  ['tomato paste', 365],
  ['coconut milk', 365],
  ['soy sauce', 180],
  ['vinegar', 730],
  ['hot sauce', 180],
  ['ketchup', 180],
  ['mustard', 180],
  ['mayo', 90],
  ['mayonnaise', 90],
  ['tahini', 180],
  ['peanut butter', 180],
  ['almond butter', 180],
  ['jam', 365],
  ['baking powder', 365],
  ['baking soda', 730],
  ['cornstarch', 730],
  ['yeast', 180],
  ['vanilla', 365],
  ['chocolate', 180],
  ['cocoa', 365],
  ['nut', 180],
  ['seed', 180],
  ['raisin', 180],

  // Spices — very long
  ['salt', 1095],
  ['pepper', 730],
  ['cumin', 730],
  ['paprika', 730],
  ['cinnamon', 730],
  ['oregano', 730],
  ['turmeric', 730],
  ['chili powder', 730],
  ['cayenne', 730],
  ['curry', 730],
  ['coriander', 730],
  ['cardamom', 730],
  ['clove', 730],
  ['nutmeg', 730],
  ['allspice', 730],
  ['bay leaf', 730],
  ['garlic powder', 730],
  ['onion powder', 730],
]

const DEFAULT_SHELF_LIFE_DAYS = 14

export function getShelfLifeDays(ingredientName: string): number {
  const lower = ingredientName.toLowerCase()
  for (const [keyword, days] of SHELF_LIFE_MAP) {
    if (lower.includes(keyword)) return days
  }
  return DEFAULT_SHELF_LIFE_DAYS
}
